### PR TITLE
Wrong post type control

### PR DESCRIPTION
**Pull request by nigrosimone**
@charlesLF w3tc has [invertet post type control](https://github.com/charlesLF/fix-w3tc/blob/w3tc-0-9-5/PgCache_Flush.php#L62)?

Eg. if `$post->post_type` is `page`, this control return `null`:

``` php
$post_type = in_array( $post->post_type, array('post', 'page', 'attachment', 'revision' ) ) ? null : $post->post_type;
```

the correct version is 

``` php
$post_type = !in_array( $post->post_type, array('post', 'page', 'attachment', 'revision' ) ) ? null : $post->post_type;
```

**This is a bug? I'm not sure**

### CODE REVIEW

**Comment by nigrosimone** [comment]
**Side note**

I find this during investigation with another issue.

From admin bar on a page: `Performance` -> `Page Modules` -> `Page cache: current page`

don't work for me, not flush the current cache for a page... I can't find where the code should do this!!

**Comment by charlesLF** [comment]
Hey @nigrosimone ,

I think the original line of code in w3tc is correct.

Let's say you have registered a custom post type (eg: `movie`) in WP, and you try to flush a single post in it, the `$post_type` shouldn't be null, it should be the post type ( `movie` ).

The reason they set it to `null` if it is one of `'post', 'page', 'attachment', 'revision'` is to flush the default RSS feed in case a post or page is flushed.
The relevant lines are in function `get_feed_link()` in `Util_PageUrls.php'

However, if you try to flush a custom post type, the function `get_feed_link()` will use the WP function `get_post_type_archive_feed_link( $post_type, $feed )` to get the feed URL (which in this case will return something like `http://domain/movie/feed/`).

**Comment by nigrosimone** [comment]
Ahh ok, thanks!

**Comment by charlesLF** [comment]
@nigrosimone with which storage engine is the "flush current page" not working?
I tried it with Redis and it was successfully deleting the keys.

**Comment by nigrosimone** [comment]
disk enhanced

**Comment by charlesLF** [comment]
I'm not able to replicate it. Disk Enhanced is being flushed correctly.

You may want to hook into `Cache_File_Generic.php` on function `delete()` and compare the `$path` variable with the path of your cache directory.
This could help you debug it.

**Comment by nigrosimone** [comment]
Ok thanks! I try to debug

**Comment by cesco69** [comment]
mhh same for me... i have performed a deep investigation. 

For me, the problem appears on multisite (network) installation path based. 

I have different site on some path, eg.:

   http://yoursite.com/en/
   http://yoursite.com/fr/

If you try to flush a page (not a post) from admin bar `Performance` > `Page Modules` > `Page cache: current page`, eg.:

```
http://yoursite.com/fr/mypage/
```

`delete()` on `Cache_File_Generic.php` try to delete:

```
/wp-content/cache/page_enhanced/yoursite.com/_index.html
/wp-content/cache/page_enhanced/yoursite.com/_index.html_gzip
/wp-content/cache/page_enhanced/yoursite.com/wp-admin/network/admin.php/_index.htm
/wp-content/cache/page_enhanced/yoursite.com/wp-admin/network/admin.php/_index.html_gzip
/wp-content/cache/page_enhanced/yoursite.com/feed/_index.html
/wp-content/cache/page_enhanced/yoursite.com/feed/_index.html_gzip
```

requested page:

```
/wp-content/cache/page_enhanced/yoursite.com/fr/mypage/_index.html
/wp-content/cache/page_enhanced/yoursite.com/fr/mypage/_index.html_gzip
```

are not in the list and the list has some mistake:

```
/wp-content/cache/page_enhanced/yoursite.com/wp-admin/network/admin.php/_index.htm
/wp-content/cache/page_enhanced/yoursite.com/wp-admin/network/admin.php/_index.html_gzip
```

i think w3tc has a large wrong implementation with the page cache flush. Another error like this is:

> Fatal error: Call to undefined method W3TC\Generic_AdminActions_Flush::flush_pgcache() in /public_html/wp-content/plugins/w3-total-cache/Generic_AdminActions_Flush.php on line 250

in this case w3tc calls method `flush_pgcache()` in class `Generic_AdminActions_Flush`, but the method not exists.

**Comment by nigrosimone** [comment]
same issue for me... the problem is simple... w3tc not have implemented the code for flush "page", i don't found it!

**Comment by nigrosimone** [comment]
@cesco69 this is the @charlesLF fork. The [main repo](https://github.com/szepeviktor/fix-w3tc) has already a branch for [0.9.5](https://github.com/szepeviktor/fix-w3tc/tree/w3tc-0-9-5). I have opened this issue on main repo https://github.com/szepeviktor/fix-w3tc/issues/136

**Comment by charlesLF** [comment]
Fix for multisite page cache flush: https://github.com/charlesLF/fix-w3tc/commit/ee1421db3e6f150179c6c72af35b01a5bd6c2460
Fix for undefined function flush_pgcache: https://github.com/charlesLF/fix-w3tc/commit/c5d72d08aba5282f4b4b910d1ba09c6044100e84

**Pull request closed without merging**
